server:
  port: 8082

spring:
  application:
    name: xlinks-router-client

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
