server:
  port: 8082

spring:
  application:
    name: xlinks-router-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.29.123:3306/xlinks_router?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 132311aA.
  data:
    redis:
      host: 123.60.29.123
      port: 6379
      password: 132311aA.
      database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: site.xlinks.ai.router.entity
  configuration:
    map-underscore-to-camel-case: true
    # 禁用 MyBatis 控制台 SQL 输出（避免 StdOutImpl 打印 SQL）
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: site.xlinks.ai.router
  paths-to-match: /**

logging:
  level:
    site.xlinks.ai.router: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

xlinks:
  # 邀请有礼链接
  promotion:
    referral-link-prefix: https://ai.xlinks.site/register?ref=
  sms:
    guoyangyun:
      host: https://gyytz.market.alicloudapi.com
      path: /sms/smsSend
      appcode: ${XLS_SMS_GYY_APP_CODE:5cf9ca38f0a94f019cb432071a715284}
      smsSignId: ${XLS_SMS_GYY_SIGN_ID:2e65b1bb3d054466b82f0c9d125465e2}
      templateId: ${XLS_SMS_GYY_TEMPLATE_ID:908e94ccf08b4476ba6c876d13f084ad}
    verify-code:
      expire-seconds: 300
      daily-limit: 20
      min-interval-seconds: 60
  email:
    mailtrap:
      access-token: ${XLS_EMAIL_MAILTRAP_ACCESS_TOKEN:}
      sender-email: ${XLS_EMAIL_MAILTRAP_SENDER_EMAIL:tech@xlinks.site}
      sender-name: ${XLS_EMAIL_MAILTRAP_SENDER_NAME:xlinks-tech}
      sender-name-template: ${XLS_EMAIL_MAILTRAP_SENDER_NAME_TEMPLATE:{appName}}
      verify-code-subject-template: "${XLS_EMAIL_MAILTRAP_VERIFY_CODE_SUBJECT_TEMPLATE:[{appName}] {sceneLabel} verification code}"
      app-name: ${XLS_EMAIL_MAILTRAP_APP_NAME:xlinks}
      api-url: ${XLS_EMAIL_MAILTRAP_API_URL:https://send.api.mailtrap.io/api/send}
      category: ${XLS_EMAIL_MAILTRAP_CATEGORY:Integration Test}
      enabled: true

# 支付宝配置
alipay:
  # 沙箱环境配置
  sandbox:
    enabled: false
    app-id: ${ALIPAY_SANDBOX_APP_ID:9021000162659038}
    private-key: ${ALIPAY_SANDBOX_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCDClQXdxR2T+GgXFK2DQ4jKdvgJnJxNIB+uASrSTwyUumjE8XjphbB4X4I7LrxKTwMMRV6mHfGD4tHb3WQv9OzVhKeNGqvujcNLHldLmYySyNg3CDS7aFeV6hQGf6UHlidKJB6hVSTYtG+416dIeHiYm94eXLDd6E1X31+VwPOqNfSHkTCAqYKb7KLEXXfhqzSl/XTdvfIncFpuWUaAJsmnwGfAxlVQWFhsdxz1bDf/k2jV2L5LPn2URRqDPD7YNtdtKvd5F0hDeQd9hINw9hVj00xzHhJeGcKTKEV/1u0JNeSrSTlv8VivlYodNmufYcogHwdorLUdiche09nHaGXAgMBAAECggEAedSpeCODR7he+lu7nnymzzSEs3KrZeq9KJNn6+Qr7lG93JtumYd6kwlVx3BpIfwHUwJziMamXONox6Kt+EUQyyRULPho1DZaJopZz7Nq2omXO9+NOO4r4G25E7gHQ6ivFHZ5VSAPEPSIM2RrO8YboAGKx8SKWYcov1mncEXwSTq7AYgyDMc71Ww86SNrK0cafm+Pe6TLcUTGx+qtoqgDDSSP/VQ4eZs0HpYZHOJP46ntxOjKIe9W/Aoa0OcDfg/Mm9YbG3ifbXjsIQd9vjy/7jEhJI+qpkW4SwtavQj91i6psTCHyEoXwm4XKvToiey1OAQm0Mq9Xf7Qc6HdsYN12QKBgQDuLGBfExmpE4+R1y1cCSJn9lQcX8pZ0Dva5BrTlMRpKUb3JZg8TYqO5ShLs2rotT/KpBxwT36BQxBmP7VnHDku3UxpWMaQS6Oi62FtTyV95w2NHSfjVZlO88gx5btzNc/WbY4S4tTKoINm95Ee58ERZho/T6pl4deYf2R/4K/HNQKBgQCM2S8MgUXDNDVT+dThxBBOxPjKWdRxRlKzB6yR02R2owjsIspifZzxOa/SNNrfvMI+uDKjIDlgcpzT4cqnMHPH3PViJXELWvp699IHLHW3RIaEgDbK0NaIh17Rx1fOkMHy/8+0YvKCI/60JcBK0xVQ/T5f6HqYlF8DHxCXUgYDGwKBgAkcY3dfmKyyFdzjWVXa95j4gFExjOEQqSl/blNHrpfDP3a21nMAGFvNAlSbAWzzegQ7cOcO82zobtkqeLsABmP3jTO+dKIScqkJzglLbMi7LPaH9f2pSZsOkkruWdRXa6LtP/ETAkbaCwzGTaPcA7OxrzFaz87j68ZmoSaPJso9AoGAElG9ONcnh7gmp4F7GtIxfM1JvqfoZcNLxlVdMKpaCsQxyOTNhfnoi8eBAso1HZyjdxzmGSl7zPubQkO/4/b9WCV5FQbhqSRwJ8ZL3vr9ZJTZGirC9aYsAR36SzauSQOy9jQng8LK3/pmim/OjuzdfOczUa4fI/FIWlOUCNp2RbkCgYEAzTZd9tZ9tkl7PPWaBQDKajKx23uZwyYE8tbSlj3nBGxGPjJxLF0fNK1Ws1wAlZrDVRigQ202R+U9u5SzYE427vErWmkTMNcftQR4z/ZzV9VY05K6QyplSGHPMgZgLMfnWUtdwiJArELbGdgCPxNgE/Xizut0ejlstJ1jGhg1xUM=}
    public-key: ${ALIPAY_SANDBOX_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgwpUF3cUdk/hoFxStg0OIynb4CZycTSAfrgEq0k8MlLpoxPF46YWweF+COy68Sk8DDEVeph3xg+LR291kL/Ts1YSnjRqr7o3DSx5XS5mMksjYNwg0u2hXleoUBn+lB5YnSiQeoVUk2LRvuNenSHh4mJveHlyw3ehNV99flcDzqjX0h5EwgKmCm+yixF134as0pf103b3yJ3BabllGgCbJp8BnwMZVUFhYbHcc9Ww3/5No1di+Sz59lEUagzw+2DbXbSr3eRdIQ3kHfYSDcPYVY9NMcx4SXhnCkyhFf9btCTXkq0k5b/FYr5WKHTZrn2HKIB8HaKy1HYnIXtPZx2hlwIDAQAB}
    alipay-public-key: ${ALIPAY_SANDBOX_ALIPAY_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnnmE+y7hGMbPa2i/oUAQgyjsTEZF/+oCvYjQlI8svpSiVE1IadScu36/fSfFeo5cBOuUcEAKRW/qgnGwqjovFTljAMD4ZMi4MJGvoJQs5+kev6sOKX0RzPHjONEd4yTbt9yqYa1JMJ3FSTFCrAuZBony1YgrRQ7q7GFhAY+MWze3Wk2mBOetUGuAS32wDxYZeDjteXo9Wyam5M/bVo/H6XTMp5pHNpBWy8HN+/gnexleAIgk6WakJTzrYZDrNE/0Z/a2f/wxK98G+Rn0kDXHpjI5lI7lwHn6xAAzH3uoy4MNKO5lKVsiCLjyjcwWHg//AcrIAkj1xu49a0sUO43/bQIDAQAB}
    gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    charset: UTF-8
    sign-type: RSA2
    format: json
    # 回调地址配置
    return-url: https://ai.xlinks.site/alipay/return
    notify-url: https://ai.xlinks.site/alipay/notify
    #payment-success-url: http://localhost:5173/payment/success
    #payment-error-url: http://localhost:5173/payment/error
    payment-success-url: https://ai.xlinks.site/alipay/payment/success
    payment-error-url: https://ai.xlinks.site/alipay/payment/error
  # 正式环境配置（预留）
  production:
    enabled: true
    app-id: ${ALIPAY_APP_ID:2021006143684229}
    private-key: ${ALIPAY_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCLP44z4TzHV6K2OGHFX/1M5tGqBfdqUHAprLfLRqorSzWIKP1Rqf3BOUItKvXdH5qHYS3Ed0flbZoy7PuCrSn7mad60FmXduwxpxKqn3PfL6T0sRqw0JSibtfxnHQ+yl/rno6qWjmSbZZHX+AuUfQYISSLHjo+wgupSv/cfZsO5rok/1V1HN6gJKzBD5E1NntgEUyYUoCHHtM55jc/DqKlO2cxEmVW1pCLlZWZPRfY3HjBoadTmyHy6DtZMAoOuiWcBVfAN+8Y4l7LsEYULcmiHjRZFUcpl+qr7f/++yKHdybbRIzmtMQuYRQmNhvRuci9oLsVcGyUZowmvLMWaneFAgMBAAECggEAJ9axGoqwVt/tv3B2GIAT+jJ3fctjM9l7nZC6rL+049oKoMAJaZnW7bcyBbYqzW7DSUQ2UeVGfo9S9Ir0kjh0sHUPg4WkfD8b6EDCiGpCPnJlIVSiLEAgpjBMO+XlJCnGM6UTcA2MNyZ/PkBh5R6xVU32JI8rXtUpfO/mL/EHscVJCJYpdhwifAd/6OW1ALM80ZkdGan0l5kmISGAR5lDw8Ls/HDrpiw6qLA67yAtywMCzUZCxxSB8zfyWfphaJH9m9SP62qGH55RLKKxi+/fUkrkUxUzr6WEVSlmjO4vtBwMrYIj/l7dBa44ajl8UzWx/ocigSrq0ySwe0wW9URiAQKBgQDF6X0Pei0UViH47o2SVGhdJ1G56xaXe0C3OVL3iqKcO4zHsmriiSctyQ3jxKdb/aYxXM8ZtQE3w/Og7DQQqDhjL1AefXgErW18RLOWhlmUyHqGPQq6bVs+a3a5cVVMjvl60e0XYsjGSjDpIYUXgtEBRS/8gx1AgBi/4Rb+a5g3wQKBgQC0Hj9DG/u3EB7iPPtSDHcZKJVt4k3D8VQ94tDjVq81SMujymCDK7sdxU2eV51JA/hLmFzqVazFBdVC07OzrGuOhGFlR4W0RMjJlVMp2hq47iTODwW7t+71V64jfK4n2/xyNP5rNrbVf1PiRG009Y/FM3LHQD+63XORdCSKrauQxQKBgQCuGDBs1vqkswf7ZE2g9SNBHn9j3ornAgLxqjlzi75zVGcIm8guMpwGSKAxRiI6Z6w0LAH6CSFjHrpHSsCaDoBbr5j42UIkSzLOZ9jahqByotA1GalASUZEaF/tzOZODE8lXVkEg18+HrFbwqLDBc45IdWOeP/YZ1ZeI/EIKTmjgQKBgE0Dmd0h+/D8TZhCptsgRVRWi/4eA05Cw9hqQRLTn7rS02/HOpkbe7hxAo0vvSrZLbN1BFWWKHdd1R/r0SyEDsEzTUm22S6JMqku1g5RGZf1C3un5LWtIdl5khXOW9DjOP/ENPy2ulpzRPS8eU1pqf2R0APuLtHBmoaY+H7rXy5ZAoGAOf62H7/BRTwpI1A/wTK7ph9cuNz0DOMEB1JuMrC5zNfO9Be0is0+QtA73T4Y75K0/TpWf9A7A7f2Y6FW9OP1/98sshpe7gn9MpZKGiWW03lnSNfmLOx/+Cdjsa0QHFsomEly10UWIs4R/DNe2zcMhp0MuyUUO4vpXM7chezrw+A=}
    public-key: ${ALIPAY_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiz+OM+E8x1eitjhhxV/9TObRqgX3alBwKay3y0aqK0s1iCj9Uan9wTlCLSr13R+ah2EtxHdH5W2aMuz7gq0p+5mnetBZl3bsMacSqp9z3y+k9LEasNCUom7X8Zx0Pspf656Oqlo5km2WR1/gLlH0GCEkix46PsILqUr/3H2bDua6JP9VdRzeoCSswQ+RNTZ7YBFMmFKAhx7TOeY3Pw6ipTtnMRJlVtaQi5WVmT0X2Nx4waGnU5sh8ug7WTAKDrolnAVXwDfvGOJey7BGFC3Joh40WRVHKZfqq+3//vsih3cm20SM5rTELmEUJjYb0bnIvaC7FXBslGaMJryzFmp3hQIDAQAB}
    alipay-public-key: ${ALIPAY_ALIPAY_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnZ8kFEsGFBL4SX4RBrbMFYHpSe9qskDBruY8rEmOHuckr1Kzqk1XIwW9DeiAwzsNxzBSTU7fcZZBELixrWfABiml/29b1I5AqmUYpHnSQUGclxypT2vrGg8oImodQrUy8QVeBDMWa7xu3zfcXjfHN63Xp9WI2mWDkAh/WnPY9WeWSmO7+a8rUZ74KVGDdgDSCHBRDPshhCuhV3WNOkdqiQIMDxQGqE3WrDxyszNSQJq+hHtPnlPSG9HIGioFoIbf/Uz9os8+0m3SXog1nmgH5yvjReRjY+6LmXUjE9onSirm61GUJq8GMDsOgiTYkcv7GY89pZ9n8HgJbEBuY8RRvwIDAQAB}
    gateway-url: https://openapi.alipay.com/gateway.do
    charset: UTF-8
    sign-type: RSA2
    format: json
    return-url: ${ALIPAY_RETURN_URL:https://ai.xlinks.site/alipay/return}
    notify-url: ${ALIPAY_NOTIFY_URL:https://ai.xlinks.site/alipay/notify}
    payment-success-url: ${ALIPAY_PAYMENT_SUCCESS_URL:https://ai.xlinks.site/payment/success}
    payment-error-url: ${ALIPAY_PAYMENT_ERROR_URL:https://ai.xlinks.site/payment/error}

