server:
  port: 8080

spring:
  application:
    name: xlinks-router-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.29.123:3306/xlinks_router?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 132311aA.
  data:
    redis:
      host: 123.60.29.123
      port: 6379
      password: 132311aA.
      database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: site.xlinks.ai.router.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# 应用配置
app:
  auth:
    sms-code-prefix: "xlinks"
    sms-code-expire-seconds: 60
    sms-send-interval-seconds: 60
    auth-token-prefix: "xlinks"
    auth-token-expire-seconds: 86400
    jwt-issuer: "xlinks-router-admin"
    jwt-secret: "2f4AlebFi0558nKePjyXhfo1YRVDtlnIbpaoj/f/tueWNfqks8D0j81FewzscqxY"
    rsa-key-size: 2048
    rsa-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyYcm3S4hNgwX/KMg8frErDOdZhyeMd4OFaOcZNHWOYAPAQEXweCosZDJyGBT4fKpZkPWdzygeICmjFspsd0rTK6TR1lX6/mALJDsDBUxQWYGi9B/kwNi9IHn0MuCsQAYJn3Foj73sJuFNSJpOlvXQVnHipoCIgs8KKO+wSQ+/QBP+SgDpTgKa6g2OkF45pN1rPoLX1BjBs71my9c4fSMDsAk+WAsrRIKzC3O9Zp1UHz/kQsAldjEWtEyV78fQ+VXfG1UEB/ufr+WaGzEyS596Y5YBCCW6r22km6XAqKPgnUhzzIVFFj7AIYdZjYHkRR9waI/HMrOlxDzLbA+4rc2tQIDAQAB"
    rsa-private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJhybdLiE2DBf8oyDx+sSsM51mHJ4x3g4Vo5xk0dY5gA8BARfB4KixkMnIYFPh8qlmQ9Z3PKB4gKaMWymx3StMrpNHWVfr+YAskOwMFTFBZgaL0H+TA2L0gefQy4KxABgmfcWiPvewm4U1Imk6W9dBWceKmgIiCzwoo77BJD79AE/5KAOlOAprqDY6QXjmk3Ws+gtfUGMGzvWbL1zh9IwOwCT5YCytEgrMLc71mnVQfP+RCwCV2MRa0TJXvx9D5Vd8bVQQH+5+v5ZobMTJLn3pjlgEIJbqvbaSbpcCoo+CdSHPMhUUWPsAhh1mNgeRFH3Boj8cys6XEPMtsD7itza1AgMBAAECggEAAwMRmiGr3mZs31pCzksMsHQvCI0p8h3bAQjKeBlIxeA7mSy+gafNbaX31hZWepyJWp1t8adG0LY/hv5/z4g6MvGzAtB7h2vZthDOblnMvCj9tQ4/Md/NlVDxuYWpJOMW+VBM6WFei1Wvtn0WrIgd3fytBk3J9V9MnWDhI3ratCZLwRNQsp55tzi2mm50I6I2YorooSvYp+ugs1bT0s5X4DE+NG0TcPpeeSdFhrxWCWkBiiRYLiH7fYAa4caUyc/s5jYE9sewhrIqX4XdpAt1wvxL755oXiTMQkRQMmZ2bQC102GkNSUzGPdZInsDaIGaQIgG1xKxgguHtIP2Zz0LsQKBgQDomV3kzHfxGjtyN2kvEnNrRwaVA/kx3RaSXyRWbU2SjBbmDJXUVoZOaoP/kUlbRi6Ba3HWShNOxD7BheZNuS1HT/VW1T4exGof3Xmc/U2fKC/2Dy/KcLcXaDvicWI3W0+BR9qIuW0I+D+x3JqPRRuA4J9acBdOwQ4wiW5ohanwfQKBgQDdzYqreXCwdkt9A76oJ+3a5SfRz6awoskVOlZA9wa2/ErKtQw97USoxhdnG7H+iIgBLdyC5vmy4Y6NE9l0hr4mWn0rrGbkqpounsAl3A5loVZNEf4ANkp4NKIvFqIByH/4lRJlVoC5qpetDWx0XwyFqi8YqKQwUiVTKR0jR+UsmQKBgDhRSgan6zKZY2NYP0OCeCe1Xsad26xTF7ABEU9Lz8h32uOAkJaFDKfX6nXqu5Q5/fCgD0QPU3Vy1q8MuKKA/5GQrpqDrzLL49YrTdLREgZDOLmfG7csa2hjeHxvb5Rvq2Rl/We1Xc0aLnHmNBYUaYBe4raHBV2wKLtfyzfLhUYRAoGBAKT9Nj+jkC3TcQfHd1VCjm4bs+kgW9Bc5tNBl9OvbXFEbqYm0rpl+oLJB7ONKHQ8P18RLEy7X9aubgmHUGSbrmp9OUr5bXh/Zz1ynWAMNzFmN/oQfi7OM8sC6/m3Dj/hU0AoM4zqMcrqmPUDXT+bTIdJNstS9v9yu40GskQCQPlRAoGALZbk6sA/vy1OOI69W1e5i8HndshKBSCXMrD+etTDTDJcG5dwpU6FnaZTYoKQF9nVAbpohfRXtR6AQOZaWRDMVssHAD82/MlPVhaScln4mZowzVAXq/FE7OMFSGI9V7VTAFm7mp8UFi4qjDQ4fNE8k5017k5ngH7xUl9ZAHGu6hY="
    sms-mock-enabled: true
  admin-auth:
    jwt-secret: "xlinks-router-admin-secret-key-2026-must-be-at-least-256-bits"
    token-expire-seconds: 86400
    bootstrap-username: "admin"
    bootstrap-password: "admin123"
    bootstrap-display-name: "Super Admin"

# SpringDoc OpenAPI 配置
#springdoc:
#  api-docs:
#    enabled: true
#    path: /v3/api-docs
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: site.xlinks.ai.router
  paths-to-match: /**


# 日志配置
logging:
  level:
    site.xlinks.ai.router: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
